// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "path";
import { defineConfig } from "prisma/config";

const defaultDbPath = path.join(process.cwd(), "data", "dev.db");
const dbPath = process.env["DB_PATH"] ?? defaultDbPath;
const databaseUrl = process.env["DATABASE_URL"] ?? `file:${dbPath}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
